### ISSUE TITLE
How to change Hostname ssh ?

### ISSUE THREAD

**Issue by villiam1999** [UTrosh/pterovm#1]
How to change Hostname ssh ?

**Comment by UTrosh** [comment]
command `hostname NAME`

**Comment by villiam1999** [comment]
where to insert it?

**Comment by UTrosh** [comment]
you can add the command in script, like when it install

**Comment by villiam1999** [comment]
> you can add the command in script, like when it install

./install.sh hostname Myhost.com 25570 ?

**Comment by UTrosh** [comment]
nah, in the script where the install is finish

**Comment by UTrosh** [comment]
no response from the user
