### ISSUE TITLE
Segmentation fault Docker

### ISSUE THREAD

**Issue by UTrosh** [UTrosh/pterovm#2]
`Segmentation fault (core dumper)` caused by a application searching memory plage that doesnt exist.

Only docker can fix it

**Comment by villiam1999** [comment]
It's not a error! The problem was in the software itself.

**Comment by UTrosh** [comment]
> 

Its a error from docker, so i add it has issue.

**Comment by UTrosh** [comment]
Docker updated for debian, issue close.
